name: test_install
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  test_install:
    runs-on: ubuntu-latest
    env:
      TERM: "linux"
    strategy:
      fail-fast: false
      matrix:
        commands:
          # Typing "1" will allow us to manually enter a path.
          # Provide a path to a writable directory: /tmp
          # Typing "99" will quit hackingtool. 
          - "1\n${HOME}/hackingtool.config\n99\n"  # Install, run, quit
          - "1\n/tmp/hackingtool\n17\n"  # Install, run, uninstall
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pwd && ls -hal
      - run: sudo ./install.sh 1
      - run: pwd && ls -hal
      - run: echo -e ${{ matrix.commands }} | hackingtool
      - run: pwd && ls -hal

